apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
    namespace: default
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:mKKWW4Jh91uMum5lTZGetAV3DK+LS8VdyoUpCaztJzo=,iv:s2Rw8exWBRy9Tez79ge7Hza1q6iIpqNPg72pic/lzTs=,tag:zAoW9lqoUo0C7npMbg43jA==,type:str]
sops:
    age:
        - recipient: age1ptrayymw5czdw2rvwr4m72xu5th7a0t6x6yugaj4txdwt7k6e55sg98zhf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcm96enV4ejd5WktpWVJI
            VUtWeU5welorZFlwNzVFeE05RzVHenIxWXlBCjdPTkVvc3ZmaFVRR0RXaFZyK2lJ
            RHc3TVE2Vy9SLzlSU25BQ0p2OWRtSlEKLS0tIFFKWkZNU0lvNmF4M0dseU04UUVw
            NVdoRXdCVzFFZW9ORTlQblltTzRWSW8Kvu3/Mq8PPq081Y1Axfdxk/ma97pFxhuy
            J0PJH5AqUYdZTAuiU/iiQ4tdEAXIP8AXazE3jrZfLoyrcSlE4MQ90w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T04:25:22Z"
    mac: ENC[AES256_GCM,data:4wNDTfCbJRAzT8+lOdXJFX6QQoT5aJToFT+1f8D2z4x22qwuk+YEqeiCL7o51/pEm8otWSAOqrg1xFkbFbt67zZ/t6ZpF/YgoLt8Quy/h00++VenMFCOjpJmHMjJ+LhlrIGjQlswyli0Pd7dgtA2k8VKnx6rVX9xCVkNCOsTh0U=,iv:0yI+uauS8rqyjg3XzZ45/KVwpcizeNs5vVp/YccWl0w=,tag:gCH/TsPPlPUQj7WokdDSVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
