apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 37.4.0
      helm:
        valueFiles:
          - $values/kubernetes/system/traefik/values.yaml
    - repoURL: https://github.com/hunsy9/homelab-platform.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/hunsy9/homelab-platform.git
      targetRevision: main
      path: kubernetes/system/traefik/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
