apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin
    namespace: keycloak
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:yv4fyNjYZuMyAsp1/XHNkLGFcZrHNTg=,iv:d56Mwqcxin8aAJy4uv4kzpjrrRhfMvV4pz7e+7gKu3Q=,tag:1+S26XHXSsfadfSvQT6xDQ==,type:str]
sops:
    age:
        - recipient: age1ptrayymw5czdw2rvwr4m72xu5th7a0t6x6yugaj4txdwt7k6e55sg98zhf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQU9uVk1FZ1lGL1A3UTdL
            Ylo5NGtpOC8vbENha1BIZ2VjVlBRMHRIbVJvCktJSS93UC9ab2JiZE12RkUvcE1r
            L29jT0JPWEJCcnl1WmViTFR4TFlKdkEKLS0tIC9jRXFJTEg5UHM2Z1JjVmpvZWIy
            WmsrNkVodWNqSDhjY1pxQ1FIdjRsK2sKk37xiJFec+j9KvNQ6H2O+QD6J8tpugpE
            rcm9LIYJ/Du9qGS69HY0MmrG9Y8QhRipe4AbBobTvbA/Nr6GX1X5Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T14:56:36Z"
    mac: ENC[AES256_GCM,data:pCAJoAucLr1ex45/RxLpU1tCd+gNFKZFyekZZDOWYXQYa9Fg6u3WL7K8SGgWSrCXegllaXLUdU2l4aSMtnSz7sFpphk+m2lvIJp1ffNhe6lmEtaincsPg04csGZwsQ72cJ4zWnNqaivw+KqG+Z1e0v0xiaWFQHJzC3ce6T2e0dA=,iv:/bJasMjfWoy4j03ub9y35X3iXkwnjvtcFK5lpuH/UeM=,tag:w3nb59yhYtviwhRIRFueLw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
