apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
  namespace: keycloak
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`keycloak.seung.site`)
      services:
        - name: keycloak-http
          port: 80
