apiVersion: v1
kind: Secret
metadata:
    name: argocd-oidc-secret
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    oidc.keycloak.clientSecret: ENC[AES256_GCM,data:rXEp6+4F2+6juQuDXKrIPm6X2xGJGusef3GaiNanQ4g=,iv:ZYR0D1V855vM4ztzvbv05NdpWWTSPo3hC5Sth4WSTAk=,tag:JeRtdAfrs9VUnkM+irbJXQ==,type:str]
sops:
    age:
        - recipient: age1ptrayymw5czdw2rvwr4m72xu5th7a0t6x6yugaj4txdwt7k6e55sg98zhf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWEpOYlNOOUVwWWhVVVFo
            R0J1S3BTdmtIdis2MUJ6RmxFL2lUaVFKb2xzCklKWTRYK2dBRXk3S2xDZ3lmL3cz
            YlMxcTBUcHkxZTZMeHpGUjBHbmZ0SHcKLS0tIEs4dFlOZFNtLytBdnpBcllKOGhS
            VURQNGFibFFwR3I2aVFQNndTUWNoQVkKSJXodFxjGGmrjUEi2v+eXM8uVD3HLNLt
            dkoEHgAs1Zf2TT/TaoKG4yRlSjJyVTfZMxb++HSwdD13Al/11lMcNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T05:13:28Z"
    mac: ENC[AES256_GCM,data:uftOHF8wJ6G+6euduNluxFihyupMZW4LnFVrKdCVo+fb57FVHBiw6hDM/rOHg2O+Wi/7s2791GbC1oU/SnN3SaknIHP1Gy8yTp7OyVNq8pM1PMytR93rakOairvYZRfhAvG/2orvOPNsIYJCFkXzAXtbagB4rlq5eWESNb6CqsI=,iv:v/TTmew1kkdaTZqMlUVmJpnMHG+M7o1/DB7CUr1AjMg=,tag:q5t3LPB3ODTgRUbMfgQL7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
