production: true
proxyHeaders: xforwarded
httpEnabled: true

auth:
  existingSecret: keycloak-admin
  passwordSecretKey: admin-password

postgresql:
  enabled: false

externalDatabase:
  host: keycloak-db-rw.keycloak.svc.cluster.local
  port: 5432
  database: keycloak
  existingSecret: keycloak-db-app
  existingSecretUserKey: username
  existingSecretPasswordKey: password
