fullnameOverride: keycloak

command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--hostname=https://keycloak.seung.site"
  - "--http-enabled=true"
  - "--http-port=8080"
  - "--proxy-headers=forwarded"
  - "--hostname-backchannel-dynamic=true"

extraEnv: |
  - name: KEYCLOAK_ADMIN
    value: admin
  - name: KEYCLOAK_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-admin
        key: admin-password

database:
  vendor: postgres
  hostname: keycloak-db-rw
  port: 5432
  database: keycloak
  username: keycloak
  existingSecret: keycloak-db-app
  existingSecretKey: password
