apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.18.2
      helm:
        valueFiles:
          - $values/kubernetes/system/harbor/values.yaml
    - repoURL: https://github.com/hunsy9/homelab-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
