apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hunsy9/homelab-platform.git
    targetRevision: main
    path: kubernetes/system/keycloak/secrets
    plugin:
      name: ksops
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
