apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.10.1
      helm:
        valueFiles:
          - $values/kubernetes/system/longhorn/values.yaml
    - repoURL: https://github.com/hunsy9/homelab-platform.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/hunsy9/homelab-platform.git
      targetRevision: main
      path: kubernetes/system/longhorn/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
