apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 80.10.0
      helm:
        valueFiles:
          - $values/kubernetes/system/monitoring/prometheus-stack/values.yaml
    - repoURL: https://github.com/hunsy9/homelab-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  ignoreDifferences:
    - kind: Secret
      name: prometheus-stack-grafana
      jsonPointers:
        - /data
    - group: apps
      kind: Deployment
      name: prometheus-stack-grafana
      jqPathExpressions:
        - .spec.template.metadata.annotations["checksum/secret"]
        - .spec.template.metadata.annotations["checksum/config"]
        - .spec.template.metadata.annotations["checksum/sc-dashboard-provider-config"]
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
